In [34]:
import numpy as np
import mltools as ml
import matplotlib.pyplot as plt 
import mltools.dtree_maxLeaves2 as dtml2
import mltools.dtree as dt
%matplotlib inline
%load_ext autoreload
%autoreload

X1 = np.genfromtxt("data/kaggle.X1.train.txt",delimiter=',')
Y = np.genfromtxt("data/kaggle.Y.train.txt",delimiter=',')

Xtr,Xva,Ytr,Yva = ml.splitData(X1,Y) 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [35]:
learner = dt.treeRegress(Xtr,Ytr,maxDepth=3)
# mlLearner = dtml2.treeRegress(Xtr,Ytr,maxLeaves=7)

[0]
[  1.   2.   3.   0.   0.   6.   0.   0.   9.  10.   0.   0.  13.   0.   0.]
[  8.   5.   4.   0.   0.   7.   0.   0.  12.  11.   0.   0.  14.   0.   0.]
[  9.  55.  83.  -1.  -1.  23.  -1.  -1.   6.  67.  -1.  -1.   6.  -1.  -1.]
[  2.41221700e+04   2.10193800e+01  -4.27132900e-01   9.66420419e-01
   4.33672270e-01   2.22895000e+04   1.61352556e+00   1.10308657e+00
   1.99954100e+02   7.96890200e+01   4.83582296e-02   3.28163014e-01
   9.50590150e+02   4.55836293e-01   8.66007309e-01]
