In [6]:
import numpy as np
np.random.seed(0)
import mltools as ml
import matplotlib.pyplot as plt   # use matplotlib for plotting with inline plots
%matplotlib inline

import mltools.dtree as dt    # import decision tree code

In [7]:
import numpy as np
import neurolab as nl
input = np.random.uniform(-0.5,0.5,(10,2))
print(input)

[[ 0.0488135   0.21518937]
 [ 0.10276338  0.04488318]
 [-0.0763452   0.14589411]
 [-0.06241279  0.391773  ]
 [ 0.46366276 -0.11655848]
 [ 0.29172504  0.02889492]
 [ 0.06804456  0.42559664]
 [-0.42896394 -0.4128707 ]
 [-0.4797816   0.33261985]
 [ 0.27815675  0.37001215]]


In [8]:
target = (input[:,0] + input[:,1]).reshape(10,1)
print(target)

[[ 0.26400287]
 [ 0.14764656]
 [ 0.06954891]
 [ 0.32936021]
 [ 0.34710428]
 [ 0.32061996]
 [ 0.4936412 ]
 [-0.84183464]
 [-0.14716176]
 [ 0.6481689 ]]


In [9]:
net = nl.net.newff([[-0.5,0.5],[-0.5,0.5]], [5,1])
print(net)

In [10]:
err = net.train(input, target, show = 15)

The goal of learning is reached


In [11]:
print(err)

[0.63868880773080072, 0.28206541695257631, 0.20688260324498803, 0.14402761412159909, 0.096768932992094908, 0.046420454619177438, 0.034462654244141001, 0.029829785200861412, 0.025501509393614476, 0.020897785856595824, 0.015843514929544479, 0.0106904536683063, 0.0073685156918519039]


In [12]:
net.sim([[0.2,0.1]])

array([[ 0.28535462]])